name: Install
description: Install dependencies

inputs:
  python-version:
    description: Python version
    default: "3.10"

runs:
  using: composite
  steps:
    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Set the python version
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip

    - name: Install python dependencies
      shell: bash
      run: pip install .[all]
